nvim/mypy: understand notes correctly
* If the first line is a note, then we would fail to include it because
  there were no diagnostics to add it. Add it as a standalone
  diagnostics if there are none to append it to
* The error code is optional but there's no way to use optional captures
  in lua regex. So, use two regexes and first try the one with error
  code and fallback to the non-error code pattern
* Hints should only be appended if it's on the same line as the previous
  diagnostic otherwise it's a standalone hint (e.g., reveal type).
  Ideally, we should also check the column numbers but I think this
  should suffice

There's still another problem that needs to be solved which is that
sometimes the diagnostics doesn't include the column numbers:

```
syntax.py:88: error: Unexpected "..."  [misc]
```

Currently, we should show them but we should!